### ISSUE TITLE
Aggregate duplicate postcodes

### ISSUE THREAD

**Issue by mtmail** [osm-uk/NI-Postcodes#3]
It's not clear how to handle duplicates in the output, it's conflicting information. Well, sometimes the difference is below 1 meter. I think those should be merged and a center calculated.

```
cut -d, -f1 NI-postcodes.csv | wc -l
   15286
cut -d, -f1 NI-postcodes.csv | sort | uniq | wc -l
    9104
```

```
BT78 3AJ,54.51637400000000,-7.45110200000000
BT78 3AJ,54.51637400000000,-7.45110100000000

BT78 4AD,54.71825210000000,-7.37651370000000
BT78 4AD,54.71803100000000,-7.37701200000000
BT78 4AD,54.71803000000000,-7.37701200000000
```

**Comment by Cj-Malone** [comment]
Nominatim already handles this. I'm not sure if it calculates the centroid on import, or on search, but either way, the more data it's given the more accurate it should be.

**Comment by mtmail** [comment]
You're right, Nominatim calculates it and then puts the result into `location_postcode` table. I remember a unique index (`CREATE UNIQUE INDEX idx_postcode_id ON location_postcode USING BTREE`) but latest version of Nominatim no longer has the `UNIQUE` clause either.
